<?php
/**
 * @file
 * A simple module to create a new Drupal page with some
 * basic CSS, HTML, PHP, & Javascript.
 * Created by:  Prof. James Barnett, Babson College 2013.
 */

/**
 * Implements hook_menu().  Hook menu declares a menu item and
 * a page for said menu item.  This is how you
 * will create custom pages.  In the below code (We'll explain more about
 * the PHP involved in a later chapter) you see simple-page is declared as the
 * url to get to this new page.  You see we define the page's title.  You see
 * we defined the page callback which basically means, go further into the
 * code and find the page callback specified (also called a function in PHP *jargon),
 * in this case simple_module_page.  Then it will execute this page *callback code specified.  We then within this callback put some HTML into *the $content variable and return that content back to render on the screen.  
 */

function simple_module_menu() {
  $items = array();
  $items['simple-page'] = array(
    'title' => 'A basic Drupal page created programmaticaly',
    'page callback' => 'simple_module_page',
    'access arguments' => array('access content'),
  );
  return $items;
}

function simple_module_page(){
  drupal_add_css(drupal_get_path('module', 'simple_module') . '/css/simple_module.css');
  drupal_add_library('system', 'ui.draggable');
  drupal_add_js(drupal_get_path('module', 'simple_module') . '/js/simple_module.js', array(
        'scope' => 'footer'));
  $content = '
    <div class="myDiv">
      <div class="bg"></div>
        <div class="block-title">A basic Drupal page created programmatically, Hello World</div>
        
        Some random text to show off this transparent background ....
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi nisi purus, gravida sit amet molestie et, facilisis vel nulla. Mauris faucibus augue eu quam feugiat at lacinia velit malesuada. Sed bibendum faucibus mattis. Maecenas quis ligula nibh, sit amet iaculis metus. Aenean lobortis massa ut nulla tristique eu vestibulum leo eleifend. Maecenas arcu lectus, facilisis in mattis sed, pretium et metus. Phasellus elementum, elit fringilla mollis sollicitudin, ipsum odio vestibulum quam, vitae tristique odio tortor eu augue. Pellentesque volutpat placerat neque, sit amet vehicula lectus commodo vitae. Aliquam nec mauris pharetra velit tincidunt consectetur. Aliquam vitae lectus nisi. Curabitur mi sapien, ultrices quis bibendum eu, ultricies eget libero. Donec mollis malesuada est a varius. Vestibulum dignissim venenatis nisl, nec semper massa tincidunt egestas. Maecenas a erat sem.

Vestibulum semper eleifend eros at semper. Phasellus neque augue, eleifend ut congue pharetra, sagittis in neque. Duis sit amet est et risus sodales vulputate sed ut sapien. Vestibulum consequat est lobortis ligula aliquam ac sodales ante sodales. Fusce dictum tortor ut est vehicula sit amet imperdiet dolor consequat. Maecenas nec risus sed quam accumsan vestibulum id ac urna. Suspendisse suscipit dictum dolor condimentum rutrum. Duis augue sem, mattis vel tincidunt ut, interdum in mauris. In quis feugiat ipsum. Donec euismod massa et tortor rhoncus lacinia. Nunc felis ligula, tincidunt eu viverra at, auctor quis magna.

Nullam sapien augue, venenatis sit amet ornare et, blandit nec velit. Morbi eu ligula a lacus commodo lacinia vel et neque. Sed at nisi at sapien adipiscing accumsan in fringilla ligula. Nunc fringilla, est vel ullamcorper tincidunt, tellus ligula lobortis turpis, vel gravida purus lacus a dui. Quisque et massa vestibulum nisi dictum lacinia vehicula ac nisi. Nulla facilisi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Phasellus sed neque ante, venenatis sagittis dui. Cras lorem ipsum, scelerisque tempor aliquet quis, imperdiet in augue. Curabitur tellus est, ultrices eu sagittis et, pellentesque id enim. Nunc lobortis mattis viverra. Sed non purus ipsum. Aenean ac justo sed urna eleifend consequat.
    </div>';
  return $content;}
