<?php
/**
 * @file
 * A simple module to create a new Drupal page with some
 * basic CSS, HTML, PHP, & Javascript.
 * Created by:  Prof. James Barnett, Babson College 2013.
 */

/**
 * Implements hook_menu().  Hook menu declares a menu item and
 * a page for said menu item.  This is how you
 * will create custom pages.  In the below code (We'll explain more about
 * the PHP involved in a later chapter) you see simple-page is declared as the
 * url to get to this new page.  You see we define the page's title.  You see
 * we defined the page callback which basically means, go further into the
 * code and find the page callback specified (also called a function in PHP *jargon),
 * in this case simple_module_page.  Then it will execute this page *callback code specified.  We then within this callback put some HTML into *the $content variable and return that content back to render on the screen.  
 */

function simple_module_menu() {
  $items = array();
  $items['simple-page'] = array(
    'title' => 'A basic Drupal page created programmaticaly',
    'page callback' => 'simple_module_page',
    'access arguments' => array('access content'),
  );
  return $items;
}

/**
 * Implements hook_theme().
 *
 * Information on hook theme http://groups.drupal.org/node/14274#comment-57950.  There are 3 basic steps to creating / using a theme fuction in Drupal.
 *    1. hook_theme which adds an array of callbacks and their arguments to the
 *      theme registry. You must clear cache before the theme function will get
 *      registered.
 *    2. The themable function itself which starts with theme_ followed by the
 *      function name that was added to the registry with hook_theme.
 *    3. Then just call your theme:  theme("whatever_function, $whatever_argument, $whatever_argument ")
 *     this actually calls the function.
 */
/*Notice that as with all functions in your module's theme you must have the name of the function begin
  by starting with your module's name then underscore then the hook name in this case -- hook theme
  is the functionality we're invoking in this case.  Whatever Drupal hook you're calling you replace the
  word hook with your module's name keep the underscore, then put the hook name you're using.  Here's a
  list of hooks .... don't worry you only need a handful of them to be very very effective
  http://api.drupal.org/api/drupal/includes%21module.inc/group/hooks/7  Hooks allow you to interract
  with Drupal core.  If you're defining your own function it's still best practice to have the first part
  of the function name begin with your module's name ..*/
function simple_module_theme() {
  return array(
    'simple_module_output' => array(
      'arguments' => array(
        'name' => NULL,
      ),
    ), 
  );
}

/**
 * Implements of hook_theme().
 *
 * @param array $variables
 *   an array with google document listings.
 *
 * @return string
 *   html with output for the user.
 */
// Notice again that we are actually declaring the theme function itself which will
// create our output and this time we do prepend the function name with theme_
function theme_simple_module_output($name) {
  /* This line below will only work if you install the devel module and is helpful in debugging,
   allowing your to 'pretty' print variables, including arrays or objects.  I strongly suggest you
   download the devel module to help you debug your programs.  http://drupal.org/project/devel*/
  dpm($name);
  /* This line below is also for debugging, and if you have the "database logging" module turned on
  (the module ships with Drupal core so no need to download it, you just need to enable it) you
  will see this log message below show up in the log (known as the watchdog log) at this url:
  http://your_url/admin/reports/dblog  You can also navigate there by clicking the "reports" and
  then "recent log messages" links from the admin menu or screen (/admin/index)*/
  watchdog('simple_module', 'got here');
  /* One last place to look for log messages I must emphasize as well is in your apache log file which
  is where you'll look for any PHP errors, definitely look there if you get a "WSOD", a "WHITE SCREEN
  OF DEATH", this is what PHP developers refer to when their page doesn't render because of a FATAL
  PHP error and you just see a white screen rather than your web page.  From Acquia dev desktop
  you can find your logs by going to the control panel, then click settings, then go to the log tab.
  In MAMP on a MAC I go to /Applications/MAMP/logs You can easily google where your apache logs are found
  by default for whatever flavor of LAMP you have installed.  If you're taking my course feel free
  to ask for help if you need it.*/
  drupal_add_css(drupal_get_path('module', 'simple_module') . '/css/simple_module.css');
  drupal_add_library('system', 'ui.draggable');
  drupal_add_js(drupal_get_path('module', 'simple_module') . '/js/simple_module.js', array(
    'scope' => 'footer'));
  // With the PHP added but keeping the CSS and JS
  $content = '<div class="myDiv">
      <div class="bg"></div>
      <p><h1>HELLO WORLD!!!!! </h1></p>';
  $x = 1;
  $my_object = new stdClass;
  $my_object->first_name = 'Jimbo';
  $my_object->last_name = 'Bob';
  $content .= 'Hello ' . $my_object->first_name . ' ' . $my_object->last_name . '</br>';
  foreach($my_object as $property) {
    $content .= 'property ' . $x . ' in the object is : '. $property . '</br>';
    $x = $x + 1;
  }
  $content .= '
        Hello World ' . $name['first_name'] . ' ' . $name['last_name'] . ' From Out Theme Function!!!!!
        
        Some random text to show off this transparent background ....
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi nisi purus, gravida sit amet molestie et, facilisis vel nulla. Mauris faucibus augue eu quam feugiat at lacinia velit malesuada. Sed bibendum faucibus mattis. Maecenas quis ligula nibh, sit amet iaculis metus. Aenean lobortis massa ut nulla tristique eu vestibulum leo eleifend. Maecenas arcu lectus, facilisis in mattis sed, pretium et metus. Phasellus elementum, elit fringilla mollis sollicitudin, ipsum odio vestibulum quam, vitae tristique odio tortor eu augue. Pellentesque volutpat placerat neque, sit amet vehicula lectus commodo vitae. Aliquam nec mauris pharetra velit tincidunt consectetur. Aliquam vitae lectus nisi. Curabitur mi sapien, ultrices quis bibendum eu, ultricies eget libero. Donec mollis malesuada est a varius. Vestibulum dignissim venenatis nisl, nec semper massa tincidunt egestas. Maecenas a erat sem.

Vestibulum semper eleifend eros at semper. Phasellus neque augue, eleifend ut congue pharetra, sagittis in neque. Duis sit amet est et risus sodales vulputate sed ut sapien. Vestibulum consequat est lobortis ligula aliquam ac sodales ante sodales. Fusce dictum tortor ut est vehicula sit amet imperdiet dolor consequat. Maecenas nec risus sed quam accumsan vestibulum id ac urna. Suspendisse suscipit dictum dolor condimentum rutrum. Duis augue sem, mattis vel tincidunt ut, interdum in mauris. In quis feugiat ipsum. Donec euismod massa et tortor rhoncus lacinia. Nunc felis ligula, tincidunt eu viverra at, auctor quis magna.

Nullam sapien augue, venenatis sit amet ornare et, blandit nec velit. Morbi eu ligula a lacus commodo lacinia vel et neque. Sed at nisi at sapien adipiscing accumsan in fringilla ligula. Nunc fringilla, est vel ullamcorper tincidunt, tellus ligula lobortis turpis, vel gravida purus lacus a dui. Quisque et massa vestibulum nisi dictum lacinia vehicula ac nisi. Nulla facilisi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Phasellus sed neque ante, venenatis sagittis dui. Cras lorem ipsum, scelerisque tempor aliquet quis, imperdiet in augue. Curabitur tellus est, ultrices eu sagittis et, pellentesque id enim. Nunc lobortis mattis viverra. Sed non purus ipsum. Aenean ac justo sed urna eleifend consequat.
    </div>';
  return $content;
}


function simple_module_page(){
  /* The below line is where we finally call our new theme function invoking it to put output on the screen */
  $content = theme('simple_module_output', array('first_name' => 'Joe', 'last_name' => 'Walton'));
  return $content;
}
