<?php
/**
 * @file
 * A simple module to create a Drupal Block programmatically,
 * which then can be placed within any region using the block system.
 * Created by:  Prof. James Barnett, Babson College 2013.
 */

function simple_block_block_info() {
  // This example comes from node.module.
  $blocks['my-block-1'] = array(
    'info' => t('My Block'), 
    'cache' => DRUPAL_NO_CACHE,
  );

  $blocks['my-block-2'] = array(
    'info' => t('My Second Block'),
    // DRUPAL_CACHE_PER_ROLE will be assumed.
  );
  return $blocks;
}

function simple_block_block_view($delta = '') {
  // This example is adapted from node.module.
  $block = array();

  switch ($delta) {
    case 'my-block-1':
      // Note wrapping your text in the t() function allows for easy
      // translations should you ever need your site to show in
      // other languages.
      $result = db_query("select n.title, u.uid, n.created from node n,
                         users u where u.uid = n.uid order by n.created desc limit 5");
      $content = "";
      foreach($result as $row){
        $content .= $row->title . '</br>';
      }
      $block['subject'] = t('My First Block');
      $block['content'] = $content;
      break;

    case 'my-block-2':
      $block['subject'] = t('My Second Block');
      $block['content'] = t('This is my second block.');
      break;
  }
  return $block;
}